### ISSUE TITLE
How to incorporate tDRnamer into tRAx workflow

### ISSUE THREAD

**Issue by sr8510** [UCSC-LoweLab/tDRnamer#1]
Hi, 

So I have been using tRAX to analyze small RNA-seq results and tRNA-seq. I tried tDRnamer so I can get the info on tDRs in my sequencing files. While the software works, I am unsure how to incorporate that into the tRAX workflow and convert the tDR annotations I get from tRAX into the tDR naming standard. 
In addition, tDRnamer does not give any counting information per tDR. Can this be done via tDRnamer? 

Thanks in advance

**Comment by patriciaplchan** [comment]
tRAX only separates tDRs by regions relatively to the source tRNAs, i.e. 5' tDRs, 3' tDRs, and mid-region, but does not provide tDR annotations in transcript level. That means the read counts grouped in a particular 5' tRNA region may include distinct tDR transcripts. If you would like to correlate those data with tDRnamer, you will need to look through the read alignments generated by tRAX and select the tDR transcripts. When using tDRnamer with fastq files as input, the number after colon in seq_name of tDR-info.txt, for example, 33 of seq_name "frag3812:33", is the raw read count of that particular tDR.
