### ISSUE TITLE
Sprinzl position in the name mismatch with the actual length

### ISSUE THREAD

**Issue by JamesRagnarok** [UCSC-LoweLab/tDRnamer#2]
I was working on a 19-nt tRF which sequenced as follows: 
`GACCGCAUAGCGCAGUGGA`

I tried the built-in Arabidopsis database with the web server and a self-built rice database (IRGSP1.0) on a local machine. Both named this tRF as "tDR-1:20-Arg-TCG-1-M2", although this tRF is only 19 nt long. I checked the alignment result and believe there's no gap or mismatch between this tRF and its tRNA origin. How could this happen? Is "1:20" in the given name correct, or I misunderstood something?
![ArgTCG__tDR_1_20_Arg_TCG_1_M2-align](https://github.com/UCSC-LoweLab/tDRnamer/assets/49954880/191a0978-1dfb-4467-9925-505ccd547a8b)

**Comment by patriciaplchan** [comment]
1:20 in the tDR name stands for Sprinzl position 1 to position 20. Sprinzl positioning does NOT layout in sequential numeric-only order. Moreover, NOT every Sprinzl position exists in every tRNA. Therefore, Sprinzl positions cannot be used to determine the sequence length unless the position mapping of the particular tRNA is available. For tRNA-Arg in Arabidopsis, positions 17 and 17a do not exist. So your tDR is correctly named. Please check out [this paper](https://doi.org/10.1093/nar/21.13.3011) regarding the description of Sprinzl positioning.

**Comment by hitaandrea** [comment]
Hello, I have a related inquiry. Could you help me finding from where I could retrieve the Sprinzl positions for the different source trna loci? In my case, I am interested in human. After running tDRnamer, I am not able to determine the sequential order of the Sprinzl positions referred in the tDR fragment id (e.g. I would like to systematically know where the intron starts and ends in fragments like this: "tDR-intron22:T9-Ile-TAT-2-3"). However, I am having trouble searching for such Sprinzl templates for each source tRNA. I cannot find this information neither among the outputs of "create_tDRnamer_db", neither "tDRnamer -m seq". Am I missing something? I would appreciate any help. Thanks

**Comment by patriciaplchan** [comment]
Sprinzl positions only apply to mature tRNAs. An intron is located between Sprinzl positions 37 and 38 at a human tRNA. For your example "tDR-intron22:T9-Ile-TAT-2-3", the fragment starts at the sequential position 22 of the intron in tRNA-Ile-TAT-2-3 and ends at position 9 of the trailer sequence of the precursor tRNA.
